In [ ]:
import pandas as pd
df = pd.read_excel("../data/ethnic_group_try3_2011.xlsx", sheet_name="Urban (total)")
df.head(10)

,KS201EW - Ethnic group,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,ONS Crown Copyright Reserved [from Nomis on 28...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,population,All usual residents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,units,Persons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,date,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,rural urban,Urban (total),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,area,NaN,All usual residents,White,White: English/Welsh/Scottish/Northern Irish/B...,White: Irish,White: Gypsy or Irish Traveller,White: Other White,Mixed/multiple ethnic groups,Mixed/multiple ethnic groups: White and Black ...,...,Asian/Asian British: Bangladeshi,Asian/Asian British: Chinese,Asian/Asian British: Other Asian,Black/African/Caribbean/Black British,Black/African/Caribbean/Black British: African,Black/African/Caribbean/Black British: Caribbean,Black/African/Caribbean/Black British: Other B...,Other ethnic group,Other ethnic group: Arab,Other ethnic group: Any other ethnic group
8,Darlington,E06000005,92363,88668,86131,285,327,1925,1043,432,...,505,317,432,345,198,102,45,232,99,133
9,County Durham,E06000047,281825,275295,270062,705,250,4278,1922,562,...,189,1229,792,480,316,101,63,593,327,266

In [ ]:
df = df[7:]
df.columns = df.iloc[0]
df = df.reset_index(drop=True)
df = df[1:]
df

7,area,NaN,All usual residents,White,White: English/Welsh/Scottish/Northern Irish/British,White: Irish,White: Gypsy or Irish Traveller,White: Other White,Mixed/multiple ethnic groups,Mixed/multiple ethnic groups: White and Black Caribbean,...,Asian/Asian British: Bangladeshi,Asian/Asian British: Chinese,Asian/Asian British: Other Asian,Black/African/Caribbean/Black British,Black/African/Caribbean/Black British: African,Black/African/Caribbean/Black British: Caribbean,Black/African/Caribbean/Black British: Other Black,Other ethnic group,Other ethnic group: Arab,Other ethnic group: Any other ethnic group
1,Darlington,E06000005,92363,88668,86131,285,327,1925,1043,432,...,505,317,432,345,198,102,45,232,99,133
2,County Durham,E06000047,281825,275295,270062,705,250,4278,1922,562,...,189,1229,792,480,316,101,63,593,327,266
3,Hartlepool,E06000001,88855,86825,85878,181,39,727,535,180,...,214,218,295,159,122,32,5,101,56,45
4,Middlesbrough,E06000002,137455,121142,118206,571,84,2281,2351,537,...,244,897,1318,1729,1468,92,169,1495,949,546
5,Northumberland,E06000057,170932,167726,165626,431,61,1608,956,249,...,233,276,458,145,100,35,10,178,42,136
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,Torfaen,W06000020,82822,81092,80207,275,134,476,561,214,...,78,185,451,159,44,84,31,88,11,77
347,Monmouthshire,W06000021,48311,47071,46056,215,2,798,383,107,...,35,156,298,79,54,19,6,82,56,26
348,Newport,W06000022,128060,113970,110037,716,70,3147,2556,1227,...,1728,550,1226,2415,1435,740,240,1386,885,501
349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,In order to protect against disclosure of pers...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.columns

Index([                                                   'area',
                                                             nan,
                                           'All usual residents',
                                                         'White',
          'White: English/Welsh/Scottish/Northern Irish/British',
                                                  'White: Irish',
                               'White: Gypsy or Irish Traveller',
                                            'White: Other White',
                                  'Mixed/multiple ethnic groups',
       'Mixed/multiple ethnic groups: White and Black Caribbean',
         'Mixed/multiple ethnic groups: White and Black African',
                 'Mixed/multiple ethnic groups: White and Asian',
                     'Mixed/multiple ethnic groups: Other Mixed',
                                           'Asian/Asian British',
                                   'Asian/Asian British: Indian',
                                'Asian/Asian British: Pakistani',
                              'Asian/Asian British: Bangladeshi',
                                  'Asian/Asian British: Chinese',
                              'Asian/Asian British: Other Asian',
                         'Black/African/Caribbean/Black British',
                'Black/African/Caribbean/Black British: African',
              'Black/African/Caribbean/Black British: Caribbean',
            'Black/African/Caribbean/Black British: Other Black',
                                            'Other ethnic group',
                                      'Other ethnic group: Arab',
                    'Other ethnic group: Any other ethnic group'],
      dtype='object', name=7)

In [ ]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df.columns = df.columns.str.replace('/', '_')
df.columns = df.columns.str.replace(':', '')
df = df.rename(columns={df.columns[1]:"nemonics"})
df.columns

Index(['area', 'nemonics', 'all_usual_residents', 'white',
       'white_english_welsh_scottish_northern_irish_british', 'white_irish',
       'white_gypsy_or_irish_traveller', 'white_other_white',
       'mixed_multiple_ethnic_groups',
       'mixed_multiple_ethnic_groups_white_and_black_caribbean',
       'mixed_multiple_ethnic_groups_white_and_black_african',
       'mixed_multiple_ethnic_groups_white_and_asian',
       'mixed_multiple_ethnic_groups_other_mixed', 'asian_asian_british',
       'asian_asian_british_indian', 'asian_asian_british_pakistani',
       'asian_asian_british_bangladeshi', 'asian_asian_british_chinese',
       'asian_asian_british_other_asian',
       'black_african_caribbean_black_british',
       'black_african_caribbean_black_british_african',
       'black_african_caribbean_black_british_caribbean',
       'black_african_caribbean_black_british_other_black',
       'other_ethnic_group', 'other_ethnic_group_arab',
       'other_ethnic_group_any_other_ethnic_group'],
      dtype='str', name=7)

In [ ]:
df.tail(3)

7,area,nemonics,all_usual_residents,white,white_english_welsh_scottish_northern_irish_british,white_irish,white_gypsy_or_irish_traveller,white_other_white,mixed_multiple_ethnic_groups,mixed_multiple_ethnic_groups_white_and_black_caribbean,...,asian_asian_british_bangladeshi,asian_asian_british_chinese,asian_asian_british_other_asian,black_african_caribbean_black_british,black_african_caribbean_black_british_african,black_african_caribbean_black_british_caribbean,black_african_caribbean_black_british_other_black,other_ethnic_group,other_ethnic_group_arab,other_ethnic_group_any_other_ethnic_group
348,Newport,W06000022,128060,113970,110037,716,70,3147,2556,1227,...,1728,550,1226,2415,1435,740,240,1386,885,501
349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,In order to protect against disclosure of pers...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.area

1                                             Darlington
2                                          County Durham
3                                             Hartlepool
4                                          Middlesbrough
5                                         Northumberland
                             ...
346                                              Torfaen
347                                        Monmouthshire
348                                              Newport
349                                                  NaN
350    In order to protect against disclosure of pers...
Name: area, Length: 350, dtype: str

In [ ]:
# df = df[df['area'].str.startswith('ua', na=False)]
df["area"].unique()

<StringArray>
[                                                                                                                                                                                                      'Darlington',
                                                                                                                                                                                                    'County Durham',
                                                                                                                                                                                                       'Hartlepool',
                                                                                                                                                                                                    'Middlesbrough',
                                                                                                                                                                                                   'Northumberland',
                                                                                                                                                                                             'Redcar and Cleveland',
                                                                                                                                                                                                 'Stockton-on-Tees',
                                                                                                                                                                                                        'Gateshead',
                                                                                                                                                                                              'Newcastle upon Tyne',
                                                                                                                                                                                                   'North Tyneside',
 ...
                                                                                                                                                                                                          'Cardiff',
                                                                                                                                                                                               'Rhondda Cynon Taff',
                                                                                                                                                                                                   'Merthyr Tydfil',
                                                                                                                                                                                                       'Caerphilly',
                                                                                                                                                                                                    'Blaenau Gwent',
                                                                                                                                                                                                          'Torfaen',
                                                                                                                                                                                                    'Monmouthshire',
                                                                                                                                                                                                          'Newport',
                                                                                                                                                                                                                nan,
 'In order to protect against disclosure of personal information, records have been swapped between different geographic areas. Some counts will be affected, particularly small counts at the lowest geographies.']
Length: 350, dtype: str

In [ ]:
df['area'] = df['area'].str.split(':').str[-1]
df["area"].unique()

array(['Darlington', 'County Durham', 'Hartlepool', 'Middlesbrough',
       'Northumberland', 'Redcar and Cleveland', 'Stockton-on-Tees',
       'Gateshead', 'Newcastle upon Tyne', 'North Tyneside',
       'South Tyneside', 'Sunderland', 'Blackburn with Darwen',
       'Blackpool', 'Cheshire East', 'Cheshire West and Chester',
       'Halton', 'Warrington', 'Allerdale', 'Barrow-in-Furness',
       'Carlisle', 'Copeland', 'Eden', 'South Lakeland', 'Bolton', 'Bury',
       'Manchester', 'Oldham', 'Rochdale', 'Salford', 'Stockport',
       'Tameside', 'Trafford', 'Wigan', 'Burnley', 'Chorley', 'Fylde',
       'Hyndburn', 'Lancaster', 'Pendle', 'Preston', 'Ribble Valley',
       'Rossendale', 'South Ribble', 'West Lancashire', 'Wyre',
       'Knowsley', 'Liverpool', 'Sefton', 'St. Helens', 'Wirral',
       'East Riding of Yorkshire', 'Kingston upon Hull, City of',
       'North East Lincolnshire', 'North Lincolnshire', 'York', 'Craven',
       'Hambleton', 'Harrogate', 'Richmondshire', 'Ryedale',
       'Scarborough', 'Selby', 'Barnsley', 'Doncaster', 'Rotherham',
       'Sheffield', 'Bradford', 'Calderdale', 'Kirklees', 'Leeds',
       'Wakefield', 'Derby', 'Leicester', 'Nottingham', 'Rutland',
       'Amber Valley', 'Bolsover', 'Chesterfield', 'Derbyshire Dales',
       'Erewash', 'High Peak', 'North East Derbyshire',
       'South Derbyshire', 'Blaby', 'Charnwood', 'Harborough',
       'Hinckley and Bosworth', 'Melton', 'North West Leicestershire',
       'Oadby and Wigston', 'Boston', 'East Lindsey', 'Lincoln',
       'North Kesteven', 'South Holland', 'South Kesteven',
       'West Lindsey', 'Corby', 'Daventry', 'East Northamptonshire',
       'Kettering', 'Northampton', 'South Northamptonshire',
       'Wellingborough', 'Ashfield', 'Bassetlaw', 'Broxtowe', 'Gedling',
       'Mansfield', 'Newark and Sherwood', 'Rushcliffe',
       'Herefordshire, County of', 'Shropshire', 'Stoke-on-Trent',
       'Telford and Wrekin', 'Cannock Chase', 'East Staffordshire',
       'Lichfield', 'Newcastle-under-Lyme', 'South Staffordshire',
       'Stafford', 'Staffordshire Moorlands', 'Tamworth',
       'North Warwickshire', 'Nuneaton and Bedworth', 'Rugby',
       'Stratford-on-Avon', 'Warwick', 'Birmingham', 'Coventry', 'Dudley',
       'Sandwell', 'Solihull', 'Walsall', 'Wolverhampton', 'Bromsgrove',
       'Malvern Hills', 'Redditch', 'Worcester', 'Wychavon',
       'Wyre Forest', 'Bedford', 'Central Bedfordshire', 'Luton',
       'Peterborough', 'Southend-on-Sea', 'Thurrock', 'Cambridge',
       'East Cambridgeshire', 'Fenland', 'Huntingdonshire',
       'South Cambridgeshire', 'Basildon', 'Braintree', 'Brentwood',
       'Castle Point', 'Chelmsford', 'Colchester', 'Epping Forest',
       'Harlow', 'Maldon', 'Rochford', 'Tendring', 'Uttlesford',
       'Broxbourne', 'Dacorum', 'East Hertfordshire', 'Hertsmere',
       'North Hertfordshire', 'St Albans', 'Stevenage', 'Three Rivers',
       'Watford', 'Welwyn Hatfield', 'Breckland', 'Broadland',
       'Great Yarmouth', "King's Lynn and West Norfolk", 'North Norfolk',
       'Norwich', 'South Norfolk', 'Babergh', 'Forest Heath', 'Ipswich',
       'Mid Suffolk', 'St Edmundsbury', 'Suffolk Coastal', 'Waveney',
       'Camden', 'City of London', 'Hackney', 'Hammersmith and Fulham',
       'Haringey', 'Islington', 'Kensington and Chelsea', 'Lambeth',
       'Lewisham', 'Newham', 'Southwark', 'Tower Hamlets', 'Wandsworth',
       'Westminster', 'Barking and Dagenham', 'Barnet', 'Bexley', 'Brent',
       'Bromley', 'Croydon', 'Ealing', 'Enfield', 'Greenwich', 'Harrow',
       'Havering', 'Hillingdon', 'Hounslow', 'Kingston upon Thames',
       'Merton', 'Redbridge', 'Richmond upon Thames', 'Sutton',
       'Waltham Forest', 'Bracknell Forest', 'Brighton and Hove',
       'Isle of Wight', 'Medway', 'Milton Keynes', 'Portsmouth',
       'Reading', 'Slough', 'Southampton', 'West Berkshire',
       'Windsor and Maidenhead', 'Wokingham', 'Aylesbury Vale',
       'Chiltern', 'South Bucks', 'Wycombe', 'Eastbourne', 'Hastings',
       'Lewes', 'Rother', 'Wealden', 'Basingstoke and Deane',
       'East Hampshire', 'Eastleigh', 'Fareham', 'Gosport', 'Hart',
       'Havant', 'New Forest', 'Rushmoor', 'Test Valley', 'Winchester',
       'Ashford', 'Canterbury', 'Dartford', 'Dover', 'Gravesham',
       'Maidstone', 'Sevenoaks', 'Folkestone and Hythe', 'Swale',
       'Thanet', 'Tonbridge and Malling', 'Tunbridge Wells', 'Cherwell',
       'Oxford', 'South Oxfordshire', 'Vale of White Horse',
       'West Oxfordshire', 'Elmbridge', 'Epsom and Ewell', 'Guildford',
       'Mole Valley', 'Reigate and Banstead', 'Runnymede', 'Spelthorne',
       'Surrey Heath', 'Tandridge', 'Waverley', 'Woking', 'Adur', 'Arun',
       'Chichester', 'Crawley', 'Horsham', 'Mid Sussex', 'Worthing',
       'Bath and North East Somerset', 'Bournemouth', 'Bristol, City of',
       'Cornwall', 'Isles of Scilly', 'North Somerset', 'Plymouth',
       'Poole', 'South Gloucestershire', 'Swindon', 'Torbay', 'Wiltshire',
       'East Devon', 'Exeter', 'Mid Devon', 'North Devon', 'South Hams',
       'Teignbridge', 'Torridge', 'West Devon', 'Christchurch',
       'East Dorset', 'North Dorset', 'Purbeck', 'West Dorset',
       'Weymouth and Portland', 'Cheltenham', 'Cotswold',
       'Forest of Dean', 'Gloucester', 'Stroud', 'Tewkesbury', 'Mendip',
       'Sedgemoor', 'South Somerset', 'Taunton Deane', 'West Somerset',
       'Isle of Anglesey', 'Gwynedd', 'Conwy', 'Denbighshire',
       'Flintshire', 'Wrexham', 'Powys', 'Ceredigion', 'Pembrokeshire',
       'Carmarthenshire', 'Swansea', 'Neath Port Talbot', 'Bridgend',
       'Vale of Glamorgan', 'Cardiff', 'Rhondda Cynon Taff',
       'Merthyr Tydfil', 'Caerphilly', 'Blaenau Gwent', 'Torfaen',
       'Monmouthshire', 'Newport', nan,
       'In order to protect against disclosure of personal information, records have been swapped between different geographic areas. Some counts will be affected, particularly small counts at the lowest geographies.'],
      dtype=object)

In [ ]:
first_nan_idx = df[df['area'].isna()].index[0]
df_cleaned = df.loc[:first_nan_idx - 1]
df.tail(3)

7,area,nemonics,all_usual_residents,white,white_english_welsh_scottish_northern_irish_british,white_irish,white_gypsy_or_irish_traveller,white_other_white,mixed_multiple_ethnic_groups,mixed_multiple_ethnic_groups_white_and_black_caribbean,...,asian_asian_british_bangladeshi,asian_asian_british_chinese,asian_asian_british_other_asian,black_african_caribbean_black_british,black_african_caribbean_black_british_african,black_african_caribbean_black_british_caribbean,black_african_caribbean_black_british_other_black,other_ethnic_group,other_ethnic_group_arab,other_ethnic_group_any_other_ethnic_group
1,Darlington,E06000005,92363,88668,86131,285,327,1925,1043,432,...,505,317,432,345,198,102,45,232,99,133
2,County Durham,E06000047,281825,275295,270062,705,250,4278,1922,562,...,189,1229,792,480,316,101,63,593,327,266
3,Hartlepool,E06000001,88855,86825,85878,181,39,727,535,180,...,214,218,295,159,122,32,5,101,56,45
4,Middlesbrough,E06000002,137455,121142,118206,571,84,2281,2351,537,...,244,897,1318,1729,1468,92,169,1495,949,546
5,Northumberland,E06000057,170932,167726,165626,431,61,1608,956,249,...,233,276,458,145,100,35,10,178,42,136

In [ ]:
df.to_csv("../data/ethnic_group_2011.csv", index=False)