# 2011 Data Read and clean trial

In [1]:
import pandas as pd
df = pd.read_excel("../data/ethnic_group_raw_2011_ks201ew.xlsx", sheet_name="Urban (total)")
df.head(10)

E:\software\conda\envs\ds\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,KS201EW - Ethnic group,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,ONS Crown Copyright Reserved [from Nomis on 28...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,population,All usual residents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,units,Persons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,date,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,rural urban,Urban (total),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,local authority: district / unitary (prior to ...,NaN,All usual residents,White,White: English/Welsh/Scottish/Northern Irish/B...,White: Irish,White: Gypsy or Irish Traveller,White: Other White,Mixed/multiple ethnic groups,Mixed/multiple ethnic groups: White and Black ...,...,Asian/Asian British: Bangladeshi,Asian/Asian British: Chinese,Asian/Asian British: Other Asian,Black/African/Caribbean/Black British,Black/African/Caribbean/Black British: African,Black/African/Caribbean/Black British: Caribbean,Black/African/Caribbean/Black British: Other B...,Other ethnic group,Other ethnic group: Arab,Other ethnic group: Any other ethnic group
8,Darlington,E06000005,92363,88668,86131,285,327,1925,1043,432,...,505,317,432,345,198,102,45,232,99,133
9,County Durham,E06000047,281825,275295,270062,705,250,4278,1922,562,...,189,1229,792,480,316,101,63,593,327,266

In [2]:
df = df[7:]
df.columns = df.iloc[0]
df = df.reset_index(drop=True)
df = df[1:]
df

7,local authority: district / unitary (prior to April 2015),NaN,All usual residents,White,White: English/Welsh/Scottish/Northern Irish/British,White: Irish,White: Gypsy or Irish Traveller,White: Other White,Mixed/multiple ethnic groups,Mixed/multiple ethnic groups: White and Black Caribbean,...,Asian/Asian British: Bangladeshi,Asian/Asian British: Chinese,Asian/Asian British: Other Asian,Black/African/Caribbean/Black British,Black/African/Caribbean/Black British: African,Black/African/Caribbean/Black British: Caribbean,Black/African/Caribbean/Black British: Other Black,Other ethnic group,Other ethnic group: Arab,Other ethnic group: Any other ethnic group
1,Darlington,E06000005,92363,88668,86131,285,327,1925,1043,432,...,505,317,432,345,198,102,45,232,99,133
2,County Durham,E06000047,281825,275295,270062,705,250,4278,1922,562,...,189,1229,792,480,316,101,63,593,327,266
3,Hartlepool,E06000001,88855,86825,85878,181,39,727,535,180,...,214,218,295,159,122,32,5,101,56,45
4,Middlesbrough,E06000002,137455,121142,118206,571,84,2281,2351,537,...,244,897,1318,1729,1468,92,169,1495,949,546
5,Northumberland,E06000057,170932,167726,165626,431,61,1608,956,249,...,233,276,458,145,100,35,10,178,42,136
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,Torfaen,W06000020,82822,81092,80207,275,134,476,561,214,...,78,185,451,159,44,84,31,88,11,77
347,Monmouthshire,W06000021,48311,47071,46056,215,2,798,383,107,...,35,156,298,79,54,19,6,82,56,26
348,Newport,W06000022,128060,113970,110037,716,70,3147,2556,1227,...,1728,550,1226,2415,1435,740,240,1386,885,501
349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,In order to protect against disclosure of pers...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.columns

Index(['local authority: district / unitary (prior to April 2015)',
                                                               nan,
                                             'All usual residents',
                                                           'White',
            'White: English/Welsh/Scottish/Northern Irish/British',
                                                    'White: Irish',
                                 'White: Gypsy or Irish Traveller',
                                              'White: Other White',
                                    'Mixed/multiple ethnic groups',
         'Mixed/multiple ethnic groups: White and Black Caribbean',
           'Mixed/multiple ethnic groups: White and Black African',
                   'Mixed/multiple ethnic groups: White and Asian',
                       'Mixed/multiple ethnic groups: Other Mixed',
                                             'Asian/Asian British',
                                     'Asian/Asian British: Indian',
                                  'Asian/Asian British: Pakistani',
                                'Asian/Asian British: Bangladeshi',
                                    'Asian/Asian British: Chinese',
                                'Asian/Asian British: Other Asian',
                           'Black/African/Caribbean/Black British',
                  'Black/African/Caribbean/Black British: African',
                'Black/African/Caribbean/Black British: Caribbean',
              'Black/African/Caribbean/Black British: Other Black',
                                              'Other ethnic group',
                                        'Other ethnic group: Arab',
                      'Other ethnic group: Any other ethnic group'],
      dtype='object', name=7)

In [4]:
df.columns = df.columns.str.lower()
df = df.rename(columns={df.columns[0]:"area"})
df.columns = df.columns.str.replace(' ', '_')
df.columns = df.columns.str.replace('/', '_')
df.columns = df.columns.str.replace(':', '')
df = df.rename(columns={df.columns[1]:"mnemonics"})
df.columns

Index(['area', 'mnemonics', 'all_usual_residents', 'white',
       'white_english_welsh_scottish_northern_irish_british', 'white_irish',
       'white_gypsy_or_irish_traveller', 'white_other_white',
       'mixed_multiple_ethnic_groups',
       'mixed_multiple_ethnic_groups_white_and_black_caribbean',
       'mixed_multiple_ethnic_groups_white_and_black_african',
       'mixed_multiple_ethnic_groups_white_and_asian',
       'mixed_multiple_ethnic_groups_other_mixed', 'asian_asian_british',
       'asian_asian_british_indian', 'asian_asian_british_pakistani',
       'asian_asian_british_bangladeshi', 'asian_asian_british_chinese',
       'asian_asian_british_other_asian',
       'black_african_caribbean_black_british',
       'black_african_caribbean_black_british_african',
       'black_african_caribbean_black_british_caribbean',
       'black_african_caribbean_black_british_other_black',
       'other_ethnic_group', 'other_ethnic_group_arab',
       'other_ethnic_group_any_other_ethnic_group'],
      dtype='str', name=7)

In [5]:
# df['area'] = df['area'].str.split(':').str[-1]
df.tail(3)

7,area,mnemonics,all_usual_residents,white,white_english_welsh_scottish_northern_irish_british,white_irish,white_gypsy_or_irish_traveller,white_other_white,mixed_multiple_ethnic_groups,mixed_multiple_ethnic_groups_white_and_black_caribbean,...,asian_asian_british_bangladeshi,asian_asian_british_chinese,asian_asian_british_other_asian,black_african_caribbean_black_british,black_african_caribbean_black_british_african,black_african_caribbean_black_british_caribbean,black_african_caribbean_black_british_other_black,other_ethnic_group,other_ethnic_group_arab,other_ethnic_group_any_other_ethnic_group
348,Newport,W06000022,128060,113970,110037,716,70,3147,2556,1227,...,1728,550,1226,2415,1435,740,240,1386,885,501
349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,In order to protect against disclosure of pers...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
first_nan_idx = df[df['area'].isna()].index[0]
df = df.loc[:first_nan_idx - 1]
df.tail(3)

7,area,mnemonics,all_usual_residents,white,white_english_welsh_scottish_northern_irish_british,white_irish,white_gypsy_or_irish_traveller,white_other_white,mixed_multiple_ethnic_groups,mixed_multiple_ethnic_groups_white_and_black_caribbean,...,asian_asian_british_bangladeshi,asian_asian_british_chinese,asian_asian_british_other_asian,black_african_caribbean_black_british,black_african_caribbean_black_british_african,black_african_caribbean_black_british_caribbean,black_african_caribbean_black_british_other_black,other_ethnic_group,other_ethnic_group_arab,other_ethnic_group_any_other_ethnic_group
346,Torfaen,W06000020,82822,81092,80207,275,134,476,561,214,...,78,185,451,159,44,84,31,88,11,77
347,Monmouthshire,W06000021,48311,47071,46056,215,2,798,383,107,...,35,156,298,79,54,19,6,82,56,26
348,Newport,W06000022,128060,113970,110037,716,70,3147,2556,1227,...,1728,550,1226,2415,1435,740,240,1386,885,501

df = df.melt(
    id_vars=['area', 'mnemonics'], 
    var_name='ethnicity_category', 
    value_name='population_count'
)

In [7]:
# df.to_csv("../data/ethnic_group_2011.csv", index=False)

# 2021 Data Read and clean trial

In [8]:
import pandas as pd

df = pd.read_excel("../data/econimic_activity_raw_2021_ts066.xlsx", sheet_name="Data")

E:\software\conda\envs\ds\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [9]:
df

,TS066 - Economic activity status,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,ONS Crown Copyright Reserved [from Nomis on 28...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,population,All usual residents aged 16 years and over,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,units,Persons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,date,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,Newport,W06000022,127420,74662,70863,62494,15978,46516,1528,377,...,69,51,18,711,50123,26175,5732,6443,7411,4362
323,Powys,W06000023,112536,62806,60699,43856,13628,30228,2614,497,...,76,52,24,219,48484,33173,3819,4004,4770,2718
324,Merthyr Tydfil,W06000024,47676,26347,25035,22007,5761,16246,623,127,...,15,11,4,237,20493,10539,1973,2263,4107,1611
325,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,In order to protect against disclosure of pers...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
header_mask = df.iloc[:, 0].astype(str).str.lower().str.startswith('local')

if header_mask.any():
    header_idx = header_mask.idxmax()
    df = df.iloc[header_idx:]
else:
    print(f"'local' not found in column 0 Falling back to row 7.")
    df = df.iloc[7:]

In [11]:
df

,TS066 - Economic activity status,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
6,local authority: district / unitary (as of Apr...,NaN,Total: All usual residents aged 16 years and over,Economically active (excluding full-time stude...,Economically active (excluding full-time stude...,Economically active (excluding full-time stude...,Economically active (excluding full-time stude...,Economically active (excluding full-time stude...,Economically active (excluding full-time stude...,Economically active (excluding full-time stude...,...,Economically active and a full-time student:In...,Economically active and a full-time student: I...,Economically active and a full-time student: I...,Economically active and a full-time student: U...,Economically inactive,Economically inactive: Retired,Economically inactive: Student,Economically inactive: Looking after home or f...,Economically inactive: Long-term sick or disabled,Economically inactive: Other
7,Hartlepool,E06000001,74685,39487,36846,32298,9575,22723,872,210,...,24,16,8,361,33934,17910,3463,4303,5432,2826
8,Middlesbrough,E06000002,113939,58233,53849,47228,14198,33030,1245,376,...,99,85,14,1431,51691,23267,7974,7527,7879,5044
9,Redcar and Cleveland,E06000003,112340,57807,54282,47224,14167,33057,1294,313,...,56,39,17,479,52716,32033,4444,5597,7268,3374
10,Stockton-on-Tees,E06000004,158008,89315,84174,73699,19945,53754,1994,462,...,69,51,18,759,65666,37038,6878,7670,8208,5872
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,Newport,W06000022,127420,74662,70863,62494,15978,46516,1528,377,...,69,51,18,711,50123,26175,5732,6443,7411,4362
323,Powys,W06000023,112536,62806,60699,43856,13628,30228,2614,497,...,76,52,24,219,48484,33173,3819,4004,4770,2718
324,Merthyr Tydfil,W06000024,47676,26347,25035,22007,5761,16246,623,127,...,15,11,4,237,20493,10539,1973,2263,4107,1611
325,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,In order to protect against disclosure of pers...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.columns = df.iloc[0]
df = df.reset_index(drop=True)
df = df[1:]

In [13]:
df

6,local authority: district / unitary (as of April 2023),NaN,Total: All usual residents aged 16 years and over,Economically active (excluding full-time students),Economically active (excluding full-time students):In employment,Economically active (excluding full-time students):In employment:Employee,Economically active (excluding full-time students): In employment: Employee: Part-time,Economically active (excluding full-time students): In employment: Employee: Full-time,Economically active (excluding full-time students):In employment:Self-employed with employees,Economically active (excluding full-time students): In employment: Self-employed with employees: Part-time,...,Economically active and a full-time student:In employment:Self-employed without employees,Economically active and a full-time student: In employment: Self-employed without employees: Part-time,Economically active and a full-time student: In employment: Self-employed without employees: Full-time,Economically active and a full-time student: Unemployed,Economically inactive,Economically inactive: Retired,Economically inactive: Student,Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other
1,Hartlepool,E06000001,74685,39487,36846,32298,9575,22723,872,210,...,24,16,8,361,33934,17910,3463,4303,5432,2826
2,Middlesbrough,E06000002,113939,58233,53849,47228,14198,33030,1245,376,...,99,85,14,1431,51691,23267,7974,7527,7879,5044
3,Redcar and Cleveland,E06000003,112340,57807,54282,47224,14167,33057,1294,313,...,56,39,17,479,52716,32033,4444,5597,7268,3374
4,Stockton-on-Tees,E06000004,158008,89315,84174,73699,19945,53754,1994,462,...,69,51,18,759,65666,37038,6878,7670,8208,5872
5,Darlington,E06000005,88103,50768,48103,42072,10748,31324,1150,258,...,32,22,10,368,35774,21930,3229,3899,4179,2537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316,Newport,W06000022,127420,74662,70863,62494,15978,46516,1528,377,...,69,51,18,711,50123,26175,5732,6443,7411,4362
317,Powys,W06000023,112536,62806,60699,43856,13628,30228,2614,497,...,76,52,24,219,48484,33173,3819,4004,4770,2718
318,Merthyr Tydfil,W06000024,47676,26347,25035,22007,5761,16246,623,127,...,15,11,4,237,20493,10539,1973,2263,4107,1611
319,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,In order to protect against disclosure of pers...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df.columns = df.columns.str.lower()  # lowering col names (personal preferrence)
# regex to clean col names
df.columns = (df.columns.str.replace(r'[ /]', '_', regex=True).str.replace(r'[:()\-]', '', regex=True))
df = df.rename(columns={df.columns[1]:"mnemonics"})
df = df.rename(columns={df.columns[0]:"area"})

# Remove the las disclaimer and nan row
first_nan_idx = df[df['area'].isna()].index[0]
df = df.loc[:first_nan_idx - 1]

In [15]:
df

6,area,mnemonics,total_all_usual_residents_aged_16_years_and_over,economically_active_excluding_fulltime_students,economically_active_excluding_fulltime_studentsin_employment,economically_active_excluding_fulltime_studentsin_employmentemployee,economically_active_excluding_fulltime_students_in_employment_employee_parttime,economically_active_excluding_fulltime_students_in_employment_employee_fulltime,economically_active_excluding_fulltime_studentsin_employmentselfemployed_with_employees,economically_active_excluding_fulltime_students_in_employment_selfemployed_with_employees_parttime,...,economically_active_and_a_fulltime_studentin_employmentselfemployed_without_employees,economically_active_and_a_fulltime_student_in_employment_selfemployed_without_employees_parttime,economically_active_and_a_fulltime_student_in_employment_selfemployed_without_employees_fulltime,economically_active_and_a_fulltime_student_unemployed,economically_inactive,economically_inactive_retired,economically_inactive_student,economically_inactive_looking_after_home_or_family,economically_inactive_longterm_sick_or_disabled,economically_inactive_other
1,Hartlepool,E06000001,74685,39487,36846,32298,9575,22723,872,210,...,24,16,8,361,33934,17910,3463,4303,5432,2826
2,Middlesbrough,E06000002,113939,58233,53849,47228,14198,33030,1245,376,...,99,85,14,1431,51691,23267,7974,7527,7879,5044
3,Redcar and Cleveland,E06000003,112340,57807,54282,47224,14167,33057,1294,313,...,56,39,17,479,52716,32033,4444,5597,7268,3374
4,Stockton-on-Tees,E06000004,158008,89315,84174,73699,19945,53754,1994,462,...,69,51,18,759,65666,37038,6878,7670,8208,5872
5,Darlington,E06000005,88103,50768,48103,42072,10748,31324,1150,258,...,32,22,10,368,35774,21930,3229,3899,4179,2537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,Torfaen,W06000020,75112,41766,39763,35275,8918,26357,775,143,...,24,19,5,284,32171,18673,2811,3455,5109,2123
315,Monmouthshire,W06000021,78238,43539,42025,33718,9140,24578,1463,321,...,51,40,11,215,33680,22877,2826,2767,3058,2152
316,Newport,W06000022,127420,74662,70863,62494,15978,46516,1528,377,...,69,51,18,711,50123,26175,5732,6443,7411,4362
317,Powys,W06000023,112536,62806,60699,43856,13628,30228,2614,497,...,76,52,24,219,48484,33173,3819,4004,4770,2718
318,Merthyr Tydfil,W06000024,47676,26347,25035,22007,5761,16246,623,127,...,15,11,4,237,20493,10539,1973,2263,4107,1611

# Changed Districts analysis

In [16]:
df_2011 = pd.read_csv("../data/clean/joins/2011.csv")
df_2021 = pd.read_csv("../data/clean/joins/2021.csv")

In [17]:
# Select only the columns that we need to understand the change
df_2011_area = df_2011[["area", "mnemonics"]]
df_2021_area = df_2021[["area", "mnemonics"]]

In [18]:
join_keys = ['area']  # Join on area name rather than code. I mean ofc, names are eaier to track.

# First find the ones that are in 2011 but not in 2021. We know there were more in 2011 than in 2021 simply by the number of rows in each file.
dist_df = pd.merge(df_2011_area, df_2021_area, on=join_keys, how='outer')
dist_df.head()

           area mnemonics_x mnemonics_y
0          Adur   E07000223   E07000223
1     Allerdale   E07000026         NaN
2  Amber Valley   E07000032   E07000032
3          Arun   E07000224   E07000224
4      Ashfield   E07000170   E07000170

In [19]:
# look of nulls in mnemonics_y col as those are the ones not in 2021
missing_2021_df = dist_df[dist_df["mnemonics_y"].isna()]
missing_2021_df.head()

                 area mnemonics_x mnemonics_y
1           Allerdale   E07000026         NaN
6      Aylesbury Vale   E07000004         NaN
11  Barrow-in-Furness   E07000027         NaN
26        Bournemouth   E06000028         NaN
52           Carlisle   E07000028         NaN

In [20]:
# Similarly find ones in 2021 but not in 2011.
dist_2_df = pd.merge(df_2011_area, df_2021_area, on=join_keys, how='right')
dist_2_df.head()

           area mnemonics_x mnemonics_y
0          Adur   E07000223   E07000223
1  Amber Valley   E07000032   E07000032
2          Arun   E07000224   E07000224
3      Ashfield   E07000170   E07000170
4       Ashford   E07000105   E07000105

In [21]:
# Same as 2011 but with otjher column instead
missing_2011_df = dist_2_df[dist_2_df["mnemonics_x"].isnull()]
missing_2011_df.head()

                                   area mnemonics_x mnemonics_y
23  Bournemouth, Christchurch and Poole         NaN   E06000058
38                      Buckinghamshire         NaN   E06000060
70                           Cumberland         NaN   E06000063
78                               Dorset         NaN   E06000059
89                         East Suffolk         NaN   E07000244

In [22]:
# tad da da we have our list of changed districts lets get deeper now
missing_2011_df = missing_2011_df.sort_values(by="mnemonics_y")
missing_2011_df

                                    area mnemonics_x mnemonics_y
23   Bournemouth, Christchurch and Poole         NaN   E06000058
78                                Dorset         NaN   E06000059
38                       Buckinghamshire         NaN   E06000060
185               North Northamptonshire         NaN   E06000061
298                West Northamptonshire         NaN   E06000062
70                            Cumberland         NaN   E06000063
302              Westmorland and Furness         NaN   E06000064
190                      North Yorkshire         NaN   E06000065
231                             Somerset         NaN   E06000066
89                          East Suffolk         NaN   E07000244
300                         West Suffolk         NaN   E07000245
210                    Rhondda Cynon Taf         NaN   W06000016

In [23]:
missing_2021_df = missing_2021_df.sort_values(by="mnemonics_x")
missing_2021_df

                       area mnemonics_x mnemonics_y
26              Bournemouth   E06000028         NaN
223                   Poole   E06000029         NaN
6            Aylesbury Vale   E07000004         NaN
65                 Chiltern   E07000005         NaN
261             South Bucks   E07000006         NaN
356                 Wycombe   E07000007         NaN
1                 Allerdale   E07000026         NaN
11        Barrow-in-Furness   E07000027         NaN
52                 Carlisle   E07000028         NaN
71                 Copeland   E07000029         NaN
105                    Eden   E07000030         NaN
268          South Lakeland   E07000031         NaN
67             Christchurch   E07000048         NaN
95              East Dorset   E07000049         NaN
198            North Dorset   E07000050         NaN
227                 Purbeck   E07000051         NaN
334             West Dorset   E07000052         NaN
343   Weymouth and Portland   E07000053         NaN
72                    Corby   E07000150         NaN
84                 Daventry   E07000151         NaN
99    East Northamptonshire   E07000152         NaN
157               Kettering   E07000153         NaN
211             Northampton   E07000154         NaN
270  South Northamptonshire   E07000155         NaN
330          Wellingborough   E07000156         NaN
77                   Craven   E07000163         NaN
130               Hambleton   E07000164         NaN
135               Harrogate   E07000165         NaN
237           Richmondshire   E07000166         NaN
248                 Ryedale   E07000167         NaN
251             Scarborough   E07000168         NaN
254                   Selby   E07000169         NaN
180                  Mendip   E07000187         NaN
252               Sedgemoor   E07000188         NaN
273          South Somerset   E07000189         NaN
301           Taunton Deane   E07000190         NaN
339           West Somerset   E07000191         NaN
116            Forest Heath   E07000201         NaN
281          St Edmundsbury   E07000204         NaN
291         Suffolk Coastal   E07000205         NaN
327                 Waveney   E07000206         NaN
234      Rhondda Cynon Taff   W06000016         NaN

Now all we need to do is fidn out whcih county from the `missing_2021_df` was merged into which counties.

[[Conversion LAD 2011 to LAD 2021](https://ckan.publishing.service.gov.uk/dataset/lsoa-2011-to-lsoa-2021-to-local-authority-district-2022-exact-fit-lookup-for-ew-v3/resource/59d599eb-43e1-4ba3-90ac-301a7e4e4da0)]: https://ckan.publishing.service.gov.uk/dataset/lsoa-2011-to-lsoa-2021-to-local-authority-district-2022-exact-fit-lookup-for-ew-v3/resource/59d599eb-43e1-4ba3-90ac-301a7e4e4da0

In [24]:
df_map = pd.read_csv('../data/clean/joins/LAD_Mapping_2011_to_2021.csv')

df_2011_mapped = pd.merge(df_2011, df_map, left_on='mnemonics', right_on='LAD2011', how='left')
df_2011_mapped['mnemonics'] = df_2011_mapped['LAD2021'].fillna(df_2011_mapped['mnemonics'])
df_2011_mapped['area'] = df_2011_mapped['LAD2021NM'].fillna(df_2011_mapped['area'])
df_2011_mapped = df_2011_mapped.drop(columns=['LAD2011NM', 'LAD2011', 'LAD2021NM', 'LAD2021'])
df_2011_agg = df_2011_mapped.groupby(['area', 'mnemonics']).sum(numeric_only=True).reset_index()

In [25]:
df_2011_agg

,area,mnemonics,all_usual_residents,white,white_english_welsh_scottish_northern_irish_british,white_irish,white_gypsy_or_irish_traveller,white_other_white,mixed_multiple_ethnic_groups,mixed_multiple_ethnic_groups_white_and_black_caribbean,...,i_accommodation_and_food_service_activities,j_information_and_communication,k_financial_and_insurance_activities,l_real_estate_activities,"m_professional,_scientific_and_technical_activities",n_administrative_and_support_service_activities,o_public_administration_and_defence;_compulsory_social_security,p_education,q_human_health_and_social_work_activities,"r,_s,_t,_u_other"
0,Adur,E07000223,61182,58663,56843,426,121,1273,886,206,...,1186,891,1613,461,1562,1332,1393,2687,4171,1459
1,Amber Valley,E07000032,122309,120023,117988,428,44,1563,980,438,...,2571,1314,961,716,2862,2274,3088,5590,7079,2591
2,Arun,E07000224,149518,145118,137024,889,162,7043,1502,426,...,4339,1899,2174,1052,3339,3509,3618,5604,9711,3711
3,Ashfield,E07000170,119497,116733,114744,348,43,1598,1059,556,...,2417,996,902,557,2020,2304,2867,4225,7474,2078
4,Ashford,E07000105,117956,110520,105498,753,531,3738,1682,544,...,2955,1710,1935,650,3519,3155,2891,5002,7255,2831
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,Wrexham,W06000006,134844,130647,125477,492,104,4574,1010,264,...,3108,1163,1779,543,2475,2802,3843,5637,9264,2581
314,Wychavon,E07000238,116944,114457,109834,539,462,3622,962,339,...,2896,1803,1630,920,3951,2852,3271,5237,6278,2682
315,Wyre,E07000128,107749,105852,104251,490,96,1015,664,234,...,3119,1135,1252,497,2286,1626,5252,4802,6495,2248
316,Wyre Forest,E07000239,97975,95273,92822,459,375,1617,998,461,...,2209,1131,955,815,2198,2055,2207,4155,5754,2296
317,York,E06000014,198051,186731,178613,1103,269,6746,2413,529,...,7805,3170,4730,1075,6164,4136,6089,12027,13113,5107

In [26]:
df_2011_agg.to_csv("../data/clean/joins/2011_cleaned.csv", index=False)